### ISSUE TITLE
Could you kindly share the trained object detection model?

### ISSUE THREAD

**Issue by hongluzhou** [ofrikleinfeld/ObjectPermanence#10]
Hi, thanks again for sharing the code and data! However, I noticed that the trained object detection model is not available. Could you kindly share the trained object detection model since I need to run your preprocessing code ('detection_model.pth' mentioned in https://github.com/ofrikleinfeld/ObjectPermanence/blob/master/configs/preprocess_config.json )? Thanks in advance!!

Best,
Honglu

**Comment by ofrikleinfeld** [comment]
I'm sorry but we currently don't have the trained object detection model.
I believe the process of creating this model is well defined in the paper.

You can try and reproduce it by using our code to generate new videos, divide them into frames, and fine-tune a FasterRCNN model as described [here](https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html)
