### ISSUE TITLE
Train different models to track different targets ??

### ISSUE THREAD

**Issue by abhaygargab** [ofrikleinfeld/ObjectPermanence#11]
Hello Authors,
Thank You for providing the code and the trained models.

Do we need to train different models to track different target objects like Cone, Cube etc. ??

Is there a way that one trained model can be used to track different objects ??

Thank You

**Comment by ofrikleinfeld** [comment]
It depends on the state of different objects.

This work focuses on localizing a single object under challenging scenarios of occlusion, containment, and carrying.
However, the "perception" module of OPNet is a simple object detection model. The output of this module is bounding box predictions **for all the visible objects**.

So, if the different objects are all visible then the localizations you are looking for might already be provided.
In more complex scenarios you'll probably have to train using a different setup or use a different model
