### ISSUE TITLE
Data download

### ISSUE THREAD

**Issue by Rajawat23** [ofrikleinfeld/ObjectPermanence#13]
Hi @ofrikleinfeld ,

Thanks for the work, 
I was wondering if it's possible to allow data download using wget. The Onedrive link you shared doesn't allow downloading using wget to training instance directly.

Thanks again in advance.

**Comment by AvivSham** [comment]
@Rajawat23 This is the only storage our university cooperates with. We talk about hundreds of GBs so I can't host it on my private storage. Have you tried to search for a solution for this problem?

**Comment by Rajawat23** [comment]
Hi @AvivSham , 
Thanks for the reply, Yeah I tried a couple of options but looks like since April 21 Microsoft changed a couple of things.
If the option to embed the link is turned on, it should provide a link that would make data downloadable using wget .
An example of embedding files.
https://support.microsoft.com/en-us/office/embed-files-directly-into-your-website-or-blog-ed07dd52-8bdb-431d-96a5-cbe8a80b7418

**Comment by AvivSham** [comment]
I wasn't able to find the "embed" option when right clicking, do you have any other suggestion? I guess one workaround (which is "stupid" way but you will be able to work) is to download it to your local computer and upload it to the server you work on.
