### ISSUE TITLE
Links to data and pretrained models

### ISSUE THREAD

**Issue by adnenabdessaied** [ofrikleinfeld/ObjectPermanence#15]
Hello Everyone,
It seems that the links to the data and pre-trained models do not work on the project site [ https://chechiklab.biu.ac.il/~avivshamsian/OP/OP_HTML.html#DatasetLinks ] anymore.

Could you please look into this.

Thanks in advance

**Comment by AvivSham** [comment]
Hi @adnenabdessaied,
Thank you for bringing this up, the links are now fixed (I also tested them on multiple devices). Would you mind to try once again and update?

**Comment by adnenabdessaied** [comment]
Thanks for fixing the links.
They work and therefore I am closing this issue.

**Comment by adnenabdessaied** [comment]
Thanks for updating the links.
They do work and therefore I am closing the issue

**Comment by finlay96** [comment]
Hi there,

Currently the link [https://chechiklab.biu.ac.il/~avivshamsian/OP/OP_HTML.html#DatasetLinks] is once again not working, is it possible that you can fix it once again?

Thanks!
