### ISSUE TITLE
Pretrained Model and Dataset link no longer working

### ISSUE THREAD

**Issue by finlay96** [ofrikleinfeld/ObjectPermanence#16]
Hi there,

Currently the link [https://chechiklab.biu.ac.il/~avivshamsian/OP/OP_HTML.html#DatasetLinks] is once again not working, is it possible that you can fix it once again?

Thanks!

**Comment by AvivSham** [comment]
Hi @finlay96,
The org policy in OneDrive requires renewing the share links every year (i.e. 365 days). I have just updated the links can you please try once again?

**Comment by finlay96** [comment]
Hi @AvivSham 

Thanks for getting back to me on this. I'm still not able to access, through this link:
`https://chechiklab.biu.ac.il/~avivshamsian/OP/OP_HTML.html#DatasetLinks`
Can you confirm this is the correct link I should be using?

Thanks!

**Comment by AvivSham** [comment]
yes, this is the correct link. Can you please share some screenshots so I will be able to better understand your issue?
you need to click it and download it via UI.

**Comment by finlay96** [comment]
![Screenshot from 2023-11-29 14-30-51](https://github.com/ofrikleinfeld/ObjectPermanence/assets/42678961/995f86c3-89ec-41ab-8c7f-c9e0586bb683)

The site just keeps loading and then ends up after a while just falling back to this. Tried on both Chrome and Firefox

**Comment by AvivSham** [comment]
Please try the [following link](https://avivsham.github.io/op_net/). It should work for you.

**Comment by finlay96** [comment]
Yep, that seems to be working! Thanks @AvivSham!
