### ISSUE TITLE
detector_tracker different to reported in paper

### ISSUE THREAD

**Issue by ysl208** [ofrikleinfeld/ObjectPermanence#6]
Hi again, I just ran the detector_tracker and the results seem to vary from the ones reported in your paper.

Mean IoU | Visible | Occluded | Contained | Carried | Overall
-- | -- | -- | -- | -- | --
Paper | 90.00+/- 0.13 | 53.00+/- 0.58 | 39.00+/- 0.38 | 34.00+/-0.40 | 71.00+/- 0.51
Recent | 88.35 | 58.81 | 31.92 | 26.19 | 67.36

my config file is as follows:

```
{
  "batch_size": 16,
  "num_workers": 12,
  "device": "cuda:0",
  "model_path": "trained_models/od_perception/detector_tracker.pth",
  "videos_dir": "data/test_data/videos",
  "sample_dir": "data/test_data/od_perception",
  "labels_dir": "data/test_data/labels",
  "scenes_dir": "data/test_data/scenes"
}
```

Is anything wrong?

**Comment by ofrikleinfeld** [comment]
It seems like you are using the code correctly.
I will check what causes this mismatch and update.

**Comment by ysl208** [comment]
Any updates on this?

**Comment by AvivSham** [comment]
closed due to inactivity
