### ISSUE TITLE
generating new data

### ISSUE THREAD

**Issue by ysl208** [ofrikleinfeld/ObjectPermanence#7]
Hi, I just tried generating new data but I seem to be getting an error message:
```
~/Projects/ObjectPermanence/generate$ python launch.py 
Found 1 GPUs. Using all of those.
Running 
        CUDA_VISIBLE_DEVICES="0"              /cortex/packages/blender-2.79b/blender             data/base_scene.blend             --background --python render_videos.py --             --num_images 3000             --start_idx 45000             --suppress_blender_logs             --save_blendfiles 0                          --max_motions=2             --output_dir <Output Directory>
    
/bin/sh: 3: Syntax error: newline unexpected
```
Any suggestions?

**Comment by ofrikleinfeld** [comment]
Generating new data is done using the blender 3D engine.  At the time, we do not provide official documentation for generating new data, but I believe you should change line 54 and specify the correct path to the blender executable.

**Comment by ysl208** [comment]
Sure, so I won't be able to generate new data and annotations? I was wondering if your data includes camera movements?

**Comment by ofrikleinfeld** [comment]
You can still use the code.
We do not provide all the available annotations, only those which are required for evaluating the OP task.
If you find more interest in generating new data with controlled annotations, you may also check out the CATER paper and codebase [https://rohitgirdhar.github.io/CATER/](https://rohitgirdhar.github.io/CATER/).
That's the codebase we built upon for new data generation.

**Comment by ysl208** [comment]
Ok Thanks. Do the 14k videos that you generated include camera movements? I had a look at a few dozens but did not see any.

**Comment by ofrikleinfeld** [comment]
No. The camera is static.
