### ISSUE TITLE
Preprocess doesn't work

### ISSUE THREAD

**Issue by ysl208** [ofrikleinfeld/ObjectPermanence#8]
Hi, I'm still new to learning models.

I tried preprocessing some video but it seems that I am missing the correct od_model? 
I am running the command 
`python main.py preprocess --results_dir results_annotations --config configs/preprocess_config.json`

Where could I get the `detection_model.pth` that corresponds to your detector? 

I passed in a different one as a test "trained_models/od_perception/detector_tracker.pth" but it doesnt have the `model_state_dict`.

I tried to trace it back, and it seems that in `detector.py` Line 62 it tries to load it and nothing after that seems to get run anymore (I put a simple print statement after it but it doesn't get print).

**Comment by ysl208** [comment]
I set  ` "od_model_weights": "trained_models/od_perception/detector_tracker.pth" ` but it seems to look for `model_state_dict` which is not a key in the saved_parameters: 
Line 62: `saved_parameters["model_state_dict"]`

Any idea?

**Comment by abhaygargab** [comment]
Hello @ofrikleinfeld, 

I am facing exactly the same issue. Can you please find some time to look into this?

Thank You

**Comment by AvivSham** [comment]
Closed due to inactivity
